    apiVersion: v1
    kind: BuildConfig
    metadata:
      name: nodejs-ex-pipeline
      labels:
        app: jenkins-pipeline-example
        name: nodejs-ex--pipeline
        template: application-template-nodejs-ex--pipeline
    spec:
      runPolicy: Serial
      strategy:
        type: JenkinsPipeline
        jenkinsPipelineStrategy:
          jenkinsfile: |-
            node('') {
              stage 'Atualiza a Build em Dev'
                openshiftBuild(namespace:'dev',buildConfig: 'nodejs-ex', showBuildLogs: 'true')
              stage 'Deploy em Dev'
                openshiftDeploy(namespace:'dev',deploymentConfig: 'nodejs-ex')
                openshiftScale(namespace:'dev',deploymentConfig: 'nodejs-ex',replicaCount: '5')
              stage 'Promove para Stage ?'
                input 'Proceeed ?'
              stage 'Atualiza a Build em Stage'
                openshiftBuild(namespace:'stage',buildConfig: 'nodejs-ex', showBuildLogs: 'true')
              stage 'Deploy em Stage'
                openshiftTag(namespace: 'stage', sourceStream: 'nodejs-ex',  sourceTag: 'latest', destinationStream: 'nodejs-ex', destinationTag: 'promoteToQA')
                openshiftDeploy(namespace:'stage',deploymentConfig: 'nodejs-ex')
                openshiftScale(namespace:'stage',deploymentConfig: 'nodejs-ex',replicaCount: '5')
              stage 'Promove para Produção ?'
                input 'Proceeed ?'
              stage 'Atualiza a Build em CI/CD'
                openshiftBuild(namespace:'cicd',buildConfig: 'nodejs-ex', showBuildLogs: 'true')
              stage 'Deploy em CI/CD'
                openshiftTag(namespace: 'cicd', sourceStream: 'nodejs-ex',  sourceTag: 'latest', destinationStream: 'nodejs-ex', destinationTag: 'promoteToProd')
                openshiftDeploy(namespace:'cicd',deploymentConfig: 'nodejs-ex')
                openshiftScale(namespace:'cicd',deploymentConfig: 'nodejs-ex',replicaCount: '5')            
            }
        type: JenkinsPipeline
      triggers:
        - github:
            secret: kH1HfX7p
          type: GitHub
        - generic:
            secret: kH1HfX7p
          type: Generic
      output:
      resources:
      postCommit:

